### ISSUE TITLE
Are you still maintaining this ?

### ISSUE THREAD

**Issue by mruiter** [KyleTaylorParkins/de.dresden-elektronik.zigbee#2]
I made a new Dresden app that supports more devices and is working with the new zigbee rewrite of homey

I wasn’t even aware there was already a Dresden app for the old firmwares :)

I submitted the new app to the AppStore and athom made me aware there was a “old” app and I should first contact you if you already had a rewrite for the AppStore ?

**Comment by KyleTaylorParkins** [comment]
Well I was (am) planning to make an version that is compatible with the v5 firmware, but since it's being delayed there was no need for it. You might want to use the icons Ivo made for the Dresden drivers to smarten up your app and take over the app store submission if you want to :)

**Comment by mruiter** [comment]
Already have the Dresden v5 app ready for store so I could take over the app if you don’t mind . I have several models of the Dresden .

Whatever you prefer . 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
V5 is about to get ready for launch and the V5 app is still waiting to be published in the store.
I know you are busy but maybee transfer the app is a solution ? You can do this in developers.athom.com under my apps on the bottom of the app page

**Comment by KyleTaylorParkins** [comment]
Like I said, transferring the app is no issue. Just send me your User ID, otherwise I can't transfer it :)

**Comment by mruiter** [comment]
I guess that’s my normal athom user account .

That user id is  mruiter@tuxweb.nl

Verstuurd vanaf mijn iPhone

**Comment by KyleTaylorParkins** [comment]
No, it's the UUID that's visible when you go to https://my.athom.com/#/, login, then select "My Account" in the top right corner. Your User ID should be at the end of the URL.

**Comment by mruiter** [comment]
Found it 🎉

567137d23710b97962117ef8

Verstuurd vanaf mijn iPhone

**Comment by KyleTaylorParkins** [comment]
It has been tranfsferred, so it should be in your app list now . Good luck with it!

**Comment by mruiter** [comment]
Great . I will push the new v5 version on top of it so v4 users can still install you’re app and v5 will use mine

Verstuurd vanaf mijn iPhone
